/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soft.appointment.presentation;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import soft.appointment.domain.Appointment;
import soft.appointment.domain.User;
import soft.appointment.persistence.UserStorage;
import soft.appointment.service.AppointmentManager;
import soft.appointment.service.EmailNotificationService;
import soft.appointment.service.LoginManager;
import soft.appointment.service.NotificationManager;

/**
 * The admin dashboard for managing appointment slots.
 * 
 * @author MoumenAbuAyyash1
 * @version 1.0
 */
public class AdminGui extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminGui.class.getName());
    
     /** Manager for appointment logic */
    private AppointmentManager appointmentManager = new AppointmentManager();
    /** Current session user */
    private User currentUser;
    /** Manager for login session */
    private LoginManager loginManager;

    /**
     * Creates new form AdminGui
     * @param user
     * @param manager
     */
    public AdminGui() {
        initComponents();
    }
    public AdminGui(soft.appointment.domain.User user, soft.appointment.service.LoginManager manager) {
        

        this.currentUser = user;
        this.loginManager = manager;
        initComponents();
        com.github.lgooddatepicker.components.DatePickerSettings dateSettings = dateTimePicker.datePicker.getSettings();
com.github.lgooddatepicker.components.TimePickerSettings timeSettings = dateTimePicker.timePicker.getSettings();
dateSettings.setAllowKeyboardEditing(false);
timeSettings.setAllowKeyboardEditing(false);
maxParticipentsSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

   
    
   
            setSafeWelcomeMessage(currentUser.getUsername());

        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dateTimePicker = new com.github.lgooddatepicker.components.DateTimePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        appointmentsTable = new javax.swing.JTable();
        addAppointmentBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        maxParticipentsSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        sendNotificationBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AdminBoard");
        setResizable(false);

        appointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "Status", "Max Capacity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        appointmentsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        appointmentsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(appointmentsTable);
        if (appointmentsTable.getColumnModel().getColumnCount() > 0) {
            appointmentsTable.getColumnModel().getColumn(0).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(1).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(2).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(3).setResizable(false);
        }

        addAppointmentBtn.setText("Add Appointment");
        addAppointmentBtn.addActionListener(this::addAppointmentBtnActionPerformed);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);

        jLabel1.setText("Admin Board");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        welcomeLabel.setText("Welcome Label");
        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        deleteBtn.setText("Delete Appointment");
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(this::refreshBtnActionPerformed);

        jLabel2.setText("Max Participents:");

        sendNotificationBtn.setText("Send Notification");
        sendNotificationBtn.addActionListener(this::sendNotificationBtnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(dateTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(maxParticipentsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addAppointmentBtn)
                                            .addComponent(deleteBtn))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sendNotificationBtn)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxParticipentsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addComponent(addAppointmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendNotificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Action performed when the add appointment button is clicked.
 * @param evt the action event
 */
    private void addAppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAppointmentBtnActionPerformed
        // TODO add your handling code here:
            int maxCap = (int) maxParticipentsSpinner.getValue(); 

             java.time.LocalDate date = dateTimePicker.datePicker.getDate();
    java.time.LocalTime time = dateTimePicker.timePicker.getTime();
    if (date == null || time == null) {
        JOptionPane.showMessageDialog(this, "Please select both Date and Time!");
        return;
    }
    Appointment newAppt = new Appointment(date, time);
        newAppt.setMaxParticipants(maxCap); 

     if (appointmentManager.addNewSlot(newAppt)) {
        JOptionPane.showMessageDialog(this, "Slot added successfully!");
        refreshTable();
    } else {
        // This triggers if the Manager says isSlotValid is false
        JOptionPane.showMessageDialog(this, "Error: You cannot create appointments in the past!");
    }
    

    }//GEN-LAST:event_addAppointmentBtnActionPerformed
/**
 * Logs out the current user and returns to login.
 * @param evt the action event
 */
    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
         loginManager.logout();
    this.dispose(); 
    new MainLoginGui().setVisible(true); 
    }//GEN-LAST:event_logoutBtnActionPerformed
/**
 * delete the appointment currently selected in the table.
 * @param evt the action event
 */
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = appointmentsTable.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a slot from the table first!");
        return;
    }
    String dateStr = appointmentsTable.getValueAt(selectedRow, 0).toString();
    String timeStr = appointmentsTable.getValueAt(selectedRow, 1).toString();
     LocalDate date = LocalDate.parse(dateStr);
    LocalTime time = LocalTime.parse(timeStr);
    Appointment toDelete = new Appointment(date, time);
        appointmentManager.removeSlot(toDelete);
JOptionPane.showMessageDialog(this, "Slot deleted successfully.");
    refreshTable();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void sendNotificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendNotificationBtnActionPerformed
        // TODO add your handling code here:
         int selectedRow = appointmentsTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select an appointment first!");
        return;
    }

    List<Appointment> allSlots = appointmentManager.getAllSlots();
    Appointment selectedAppt = allSlots.get(selectedRow);
    if (selectedAppt.getParticipants().isEmpty()) {
        JOptionPane.showMessageDialog(this, "This slot has no participants yet. No one to notify!");
        return; 
    }

    NotificationManager nm = new NotificationManager();
    nm.addObserver(new EmailNotificationService()); 

    UserStorage userStorage = new UserStorage();
    
    appointmentManager.sendReminders(selectedAppt, nm, userStorage);

    JOptionPane.showMessageDialog(this, "Notifications sent to all participants!");
    }//GEN-LAST:event_sendNotificationBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminGui().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAppointmentBtn;
    private javax.swing.JTable appointmentsTable;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JSpinner maxParticipentsSpinner;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton sendNotificationBtn;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
/**
 * get data from manager and fill the table.
 */
   private void refreshTable() {
    DefaultTableModel model = (DefaultTableModel) appointmentsTable.getModel();
    model.setRowCount(0); 

List<soft.appointment.domain.Appointment> list = appointmentManager.getAllSlots();

    for (soft.appointment.domain.Appointment a : list) {
        model.addRow(new Object[]{
            a.getDate(), 
            a.getStartTime(), 
            a.isAvailable() ? "Available" : "Booked",
            a.getMaxParticipants() 
        });
    }
}
   /**
 * Sets the welcome message with a safety check for long names.
 * @param username the name to display
 */
private void setSafeWelcomeMessage(String username) {
    String displayName = username;
    
    if (username.length() > 15) {
        displayName = username.substring(0, 12) + "...";
    }
    
    welcomeLabel.setText("Hello, " + displayName);
}
}
